# should not be changed as of now as it will only extract 0 and 1 index values only
# need to change the string in scraper, if want to add more parameters
PARAMS = {
    'name': ['PM2.5', 
    'PM10', 
    'NO2', 
    'SO2',
    'CO',
    'Ozone',
    ],

    'value': [
    'parameter_193', 
    'parameter_215', 
    'parameter_194', 
    'parameter_312',
    'parameter_203',
    'parameter_222',
    ]
}

# website address
HEADER = 'https://app.cpcbccr.com/ccr/#/caaqm-dashboard-all/caaqm-view-data-report/'
# change this xpath with pdf or word xpath to get pdf or word file instead of xlsx
XPATH = '/html/body/app-root/app-caaqm-dashboard/div[1]/div/main/section/app-caaqm-view-data-report/div[2]/div[1]/div[2]/div/div/a[2]/i'

# start and end date  = format(Day, Month, Year)
start_date = '01-01-2018'
end_date = '01-01-2019'

# criteria or interval
# requires changes in string in scraper if wanted to change criteria from hours to minutes or annual average
criteria = 24  # available criteria [1, 4, 8, 24 hours]

# Downloads folder path - changes to your own path
downloads_folder = 'C:\\Users\\manje\\Downloads\\'

# set state == '' to download all cities and states
STATE = 'Delhi'

# 'Mumbai', 'Kolkata', 'Chennai', 'Delhi', 'Bengaluru'

STATIONS_LIST = [{'state': 'Delhi',
  'city': 'Delhi',
  'site': 'site_301',
  'site_name': 'Anand Vihar, Delhi - DPCC'},
 {'state': 'Delhi',
  'city': 'Delhi',
  'site': 'site_1420',
  'site_name': 'Ashok Vihar, Delhi - DPCC'},
 {'state': 'Delhi',
  'city': 'Delhi',
  'site': 'site_108',
  'site_name': 'Aya Nagar, New Delhi - IMD'},
 {'state': 'Delhi',
  'city': 'Delhi',
  'site': 'site_1560',
  'site_name': 'Bawana, Delhi - DPCC'},
 {'state': 'Delhi',
  'city': 'Delhi',
  'site': 'site_104',
  'site_name': 'Burari Crossing, New Delhi - IMD'},
 {'state': 'Delhi',
  'city': 'Delhi',
  'site': 'site_103',
  'site_name': 'CRRI Mathura Road, New Delhi - IMD'},
 {'state': 'Delhi',
  'city': 'Delhi',
  'site': 'site_118',
  'site_name': 'DTU, New Delhi - CPCB'},
 {'state': 'Delhi',
  'city': 'Delhi',
  'site': 'site_1421',
  'site_name': 'Dr. Karni Singh Shooting Range, Delhi - DPCC'},
 {'state': 'Delhi',
  'city': 'Delhi',
  'site': 'site_1422',
  'site_name': 'Dwarka-Sector 8, Delhi - DPCC'},
 {'state': 'Delhi',
  'city': 'Delhi',
  'site': 'site_106',
  'site_name': 'IGI Airport (T3), New Delhi - IMD'},
 {'state': 'Delhi',
  'city': 'Delhi',
  'site': 'site_114',
  'site_name': 'IHBAS, Dilshad Garden,New Delhi - CPCB'},
 {'state': 'Delhi',
  'city': 'Delhi',
  'site': 'site_117',
  'site_name': 'ITO, New Delhi - CPCB'},
 {'state': 'Delhi',
  'city': 'Delhi',
  'site': 'site_1423',
  'site_name': 'Jahangirpuri, Delhi - DPCC'},
 {'state': 'Delhi',
  'city': 'Delhi',
  'site': 'site_1424',
  'site_name': 'Jawaharlal Nehru Stadium, Delhi - DPCC'},
 {'state': 'Delhi',
  'city': 'Delhi',
  'site': 'site_109',
  'site_name': 'Lodhi Road, New Delhi - IMD'},
 {'state': 'Delhi',
  'city': 'Delhi',
  'site': 'site_1425',
  'site_name': 'Major Dhyan Chand National Stadium, Delhi - DPCC'},
 {'state': 'Delhi',
  'city': 'Delhi',
  'site': 'site_122',
  'site_name': 'Mandir Marg, New Delhi - DPCC'},
 {'state': 'Delhi',
  'city': 'Delhi',
  'site': 'site_1561',
  'site_name': 'Mundaka, Delhi - DPCC'},
 {'state': 'Delhi',
  'city': 'Delhi',
  'site': 'site_115',
  'site_name': 'NSIT Dwarka, New Delhi - CPCB'},
 {'state': 'Delhi',
  'city': 'Delhi',
  'site': 'site_1427',
  'site_name': 'Najafgarh, Delhi - DPCC'},
 {'state': 'Delhi',
  'city': 'Delhi',
  'site': 'site_1426',
  'site_name': 'Narela, Delhi - DPCC'},
 {'state': 'Delhi',
  'city': 'Delhi',
  'site': 'site_1429',
  'site_name': 'Nehru Nagar, Delhi - DPCC'},
 {'state': 'Delhi',
  'city': 'Delhi',
  'site': 'site_105',
  'site_name': 'North Campus, DU, New Delhi - IMD'},
 {'state': 'Delhi',
  'city': 'Delhi',
  'site': 'site_1428',
  'site_name': 'Okhla Phase-2, Delhi - DPCC'},
 {'state': 'Delhi',
  'city': 'Delhi',
  'site': 'site_1431',
  'site_name': 'Patparganj, Delhi - DPCC'},
 {'state': 'Delhi',
  'city': 'Delhi',
  'site': 'site_125',
  'site_name': 'Punjabi Bagh, Delhi - DPCC'},
 {'state': 'Delhi',
  'city': 'Delhi',
  'site': 'site_107',
  'site_name': 'Pusa, New Delhi - IMD'},
 {'state': 'Delhi',
  'city': 'Delhi',
  'site': 'site_124',
  'site_name': 'R K Puram, New Delhi - DPCC'},
 {'state': 'Delhi',
  'city': 'Delhi',
  'site': 'site_1430',
  'site_name': 'Rohini, Delhi - DPCC'},
 {'state': 'Delhi',
  'city': 'Delhi',
  'site': 'site_113',
  'site_name': 'Shadipur, New Delhi - CPCB'},
 {'state': 'Delhi',
  'city': 'Delhi',
  'site': 'site_119',
  'site_name': 'Sirifort, New Delhi - CPCB'},
 {'state': 'Delhi',
  'city': 'Delhi',
  'site': 'site_1432',
  'site_name': 'Sonia Vihar, Delhi - DPCC'},
 {'state': 'Delhi',
  'city': 'Delhi',
  'site': 'site_1562',
  'site_name': 'Sri Aurobindo Marg, Delhi - DPCC'},
 {'state': 'Delhi',
  'city': 'Delhi',
  'site': 'site_1435',
  'site_name': 'Vivek Vihar, Delhi - DPCC'},
 {'state': 'Delhi',
  'city': 'Delhi',
  'site': 'site_1434',
  'site_name': 'Wazirpur, Delhi - DPCC'},
 {'state': 'Delhi',
  'city': 'Delhi',
  'site': 'site_5024',
  'site_name': 'Alipur, Delhi - DPCC'},
 {'state': 'Delhi',
  'city': 'Delhi',
  'site': 'site_5393',
  'site_name': 'Chandni Chowk, Delhi - IITM'},
 {'state': 'Maharashtra',
  'city': 'Mumbai',
  'site': 'site_5392',
  'site_name': 'Bandra Kurla Complex, Mumbai - IITM'},
 {'state': 'Maharashtra',
  'city': 'Mumbai',
  'site': 'site_168',
  'site_name': 'Bandra, Mumbai - MPCB'},
 {'state': 'Maharashtra',
  'city': 'Mumbai',
  'site': 'site_5400',
  'site_name': 'Borivali East, Mumbai - IITM'},
 {'state': 'Maharashtra',
  'city': 'Mumbai',
  'site': 'site_5113',
  'site_name': 'Borivali East, Mumbai - MPCB'},
 {'state': 'Maharashtra',
  'city': 'Mumbai',
  'site': 'site_5399',
  'site_name': 'Chakala-Andheri East, Mumbai - IITM'},
 {'state': 'Maharashtra',
  'city': 'Mumbai',
  'site': 'site_5107',
  'site_name': 'Chhatrapati Shivaji Intl. Airport (T2), Mumbai -MPCB'},
 {'state': 'Maharashtra',
  'city': 'Mumbai',
  'site': 'site_5120',
  'site_name': 'Colaba, Mumbai - MPCB'},
 {'state': 'Maharashtra',
  'city': 'Mumbai',
  'site': 'site_5396',
  'site_name': 'Deonar, Mumbai - IITM'},
 {'state': 'Maharashtra',
  'city': 'Mumbai',
  'site': 'site_5412',
  'site_name': 'Kandivali East, Mumbai - MPCB'},
 {'state': 'Maharashtra',
  'city': 'Mumbai',
  'site': 'site_5397',
  'site_name': 'Khindipada-Bhandup West, Mumbai - IITM'},
 {'state': 'Maharashtra',
  'city': 'Mumbai',
  'site': 'site_5104',
  'site_name': 'Kurla, Mumbai - MPCB'},
 {'state': 'Maharashtra',
  'city': 'Mumbai',
  'site': 'site_5402',
  'site_name': 'Malad West, Mumbai - IITM'},
 {'state': 'Maharashtra',
  'city': 'Mumbai',
  'site': 'site_5394',
  'site_name': 'Mazgaon, Mumbai - IITM'},
 {'state': 'Maharashtra',
  'city': 'Mumbai',
  'site': 'site_5413',
  'site_name': 'Mulund West, Mumbai - MPCB'},
 {'state': 'Maharashtra',
  'city': 'Mumbai',
  'site': 'site_5398',
  'site_name': 'Navy Nagar-Colaba, Mumbai - IITM'},
 {'state': 'Maharashtra',
  'city': 'Mumbai',
  'site': 'site_5112',
  'site_name': 'Powai, Mumbai - MPCB'},
 {'state': 'Maharashtra',
  'city': 'Mumbai',
  'site': 'site_5403',
  'site_name': 'Siddharth Nagar-Worli, Mumbai - IITM'},
 {'state': 'Maharashtra',
  'city': 'Mumbai',
  'site': 'site_5119',
  'site_name': 'Sion, Mumbai - MPCB'},
 {'state': 'Maharashtra',
  'city': 'Mumbai',
  'site': 'site_5102',
  'site_name': 'Vasai West, Mumbai - MPCB'},
 {'state': 'Maharashtra',
  'city': 'Mumbai',
  'site': 'site_5106',
  'site_name': 'Vile Parle West, Mumbai - MPCB'},
 {'state': 'Maharashtra',
  'city': 'Mumbai',
  'site': 'site_5115',
  'site_name': 'Worli, Mumbai - MPCB'},
 {'state': 'West Bengal',
  'city': 'Kolkata',
  'site': 'site_5238',
  'site_name': 'Ballygunge, Kolkata - WBPCB'},
 {'state': 'West Bengal',
  'city': 'Kolkata',
  'site': 'site_5129',
  'site_name': 'Bidhannagar, Kolkata - WBPCB'},
 {'state': 'West Bengal',
  'city': 'Kolkata',
  'site': 'site_5110',
  'site_name': 'Fort William, Kolkata - WBPCB'},
 {'state': 'West Bengal',
  'city': 'Kolkata',
  'site': 'site_5111',
  'site_name': 'Jadavpur, Kolkata - WBPCB'},
 {'state': 'West Bengal',
  'city': 'Kolkata',
  'site': 'site_5126',
  'site_name': 'Rabindra Sarobar, Kolkata - WBPCB'},
 {'state': 'Tamil Nadu',
  'city': 'Chennai',
  'site': 'site_293',
  'site_name': 'Alandur Bus Deport, Chennai - CPCB'},
 {'state': 'Tamil Nadu',
  'city': 'Chennai',
  'site': 'site_5361',
  'site_name': 'Arumbakkam, Chennai - TNPCB'},
 {'state': 'Tamil Nadu',
  'city': 'Chennai',
  'site': 'site_5365',
  'site_name': 'Kodungaiyur, Chennai - TNPCB'},
 {'state': 'Tamil Nadu',
  'city': 'Chennai',
  'site': 'site_5092',
  'site_name': 'Manali Village, Chennai - TNPCB'},
 {'state': 'Tamil Nadu',
  'city': 'Chennai',
  'site': 'site_306',
  'site_name': 'Manali, Chennai - CPCB'},
 {'state': 'Tamil Nadu',
  'city': 'Chennai',
  'site': 'site_5363',
  'site_name': 'Perungudi, Chennai - TNPCB'},
 {'state': 'Tamil Nadu',
  'city': 'Chennai',
  'site': 'site_5364',
  'site_name': 'Royapuram, Chennai - TNPCB'},
 {'state': 'Tamil Nadu',
  'city': 'Chennai',
  'site': 'site_288',
  'site_name': 'Velanchery Res. Area, Chennai - CPCB'},
 {'state': 'Karnataka',
  'city': 'Bengaluru',
  'site': 'site_162',
  'site_name': 'BTM Layout, Bengaluru - CPCB'},
 {'state': 'Karnataka',
  'city': 'Bengaluru',
  'site': 'site_164',
  'site_name': 'BWSSB Kadabesanahalli, Bengaluru - CPCB'},
 {'state': 'Karnataka',
  'city': 'Bengaluru',
  'site': 'site_1553',
  'site_name': 'Bapuji Nagar, Bengaluru - KSPCB'},
 {'state': 'Karnataka',
  'city': 'Bengaluru',
  'site': 'site_1554',
  'site_name': 'Hebbal, Bengaluru - KSPCB'},
 {'state': 'Karnataka',
  'city': 'Bengaluru',
  'site': 'site_1555',
  'site_name': 'Hombegowda Nagar, Bengaluru - KSPCB'},
 {'state': 'Karnataka',
  'city': 'Bengaluru',
  'site': 'site_1556',
  'site_name': 'Jayanagar 5th Block, Bengaluru - KSPCB'},
 {'state': 'Karnataka',
  'city': 'Bengaluru',
  'site': 'site_163',
  'site_name': 'Peenya, Bengaluru - CPCB'},
 {'state': 'Karnataka',
  'city': 'Bengaluru',
  'site': 'site_1558',
  'site_name': 'Silk Board, Bengaluru - KSPCB'}]
